apiVersion: v1
kind: Pod
metadata:
  name: k8s-restify
  labels:
    version: v1.0
    app: k8s-restify
spec:
  containers:
    - name: k8s-restify
      image: k8s-restify:1.0
      ports:
        - containerPort: 8080
